name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag canberkglr/gittest:latest
      
    - name: Login to Docker Hub
    - uses: docker/login-action@v3
      with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
    - name: Push image
      run: docker push canberkglr/gittest:latest


  pull:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push Docker image
      run: docker pull canberkglr/gittest:latest
