name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: canberkglr/gittest:latest


  pull:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Push Docker image
      run: docker pull canberkglr/gittest:latest
